### ISSUE TITLE
What are the requirements?

### ISSUE THREAD

**Issue by maxolasersquad** [ChrisRx/dungeonfs#5]
I'm running Ubuntu 16.04 and I installed the `golang` package. When I use the instructions in the README I get
```sh
$ go get github.com/ChrisRx/dungeonfs...        
package github.com/ChrisRx/dungeonfs...: cannot expand ... in "github.com/ChrisRx/dungeonfs..."
```

Am I missing a required package?

**Comment by ChrisRx** [comment]
Hmmm, try `go get github.com/ChrisRx/dungeonfs/...` instead.  It looks like it is failing when the directory doesn't already exist with the other command.

**Comment by maxolasersquad** [comment]
Here's the instructions I needed to get it installed.

```
sudo apt install golang
sudo su
export GOPATH="/usr/share/go/"
go get -u github.com/ChrisRx/dungeonfs...
```

**Comment by ChrisRx** [comment]
did you try `go get github.com/ChrisRx/dungeonfs/...`?  I believe that would have fixed your issue.

**Comment by maxolasersquad** [comment]
Yes. It gave me permission errors trying to create directories under `/usr/share/go`

**Comment by ChrisRx** [comment]
Ok good that means that it would have indeed fixed your issue.  You ran into those errors because your Go environment was setup incorrectly.  With all version of Go before 1.7 you must set your GOPATH and have it set to something that your user has the permissions to run.  By setting your GOPATH it resolved your environment issue.
